### ISSUE TITLE
Issue: Implement Header Section

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Frontend#11]
Create the header section with the greeting text ("Subho Sarodiya" / "শুভ শারদীয়া") and settings icon. Ensure the greeting text is dynamic and can change based on the user's language settings. The settings icon should be clickable and navigate to the settings screen.

Check this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=386-8094&t=20CVJBgMkxb3Icl4-1) and this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=388-8845&t=20CVJBgMkxb3Icl4-1)

**Comment by hema-k83** [comment]
@TheHappyBaloney Can you please assign this to me
