### ISSUE TITLE
Create Search Bar Component

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Frontend#12]
Develop the search bar with an input field and three quick-access icons for "Transport" "Pharmacy," and "ATMs." The search bar should be functional and filter content based on user input.

Check this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=386-8094&t=20CVJBgMkxb3Icl4-1) and this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=388-8845&t=20CVJBgMkxb3Icl4-1)

**Comment by aizaysi** [comment]
let me try this.

**Comment by TheHappyBaloney** [comment]
> let me try this.

Go ahead

**Comment by aizaysi** [comment]
let me push my branch, this repo refuses my access
![image](https://github.com/user-attachments/assets/3b2b17f0-9146-46f2-a7c5-abf8ecb7bc6a)

**Comment by hema-k83** [comment]
You can't directly push you have to raise a PR. 

1. Fork dev branch
2. Create a new branch from that fork, please use branch names such as feature/name, bug/name etc. Based on the type of work you are contributing to repo.
3. Push your changes to newly created branch.
4. Raise a PR to dev with those changes. Changes will be reviewed and merged.

**Comment by aizaysi** [comment]
thanks for your advice.
I did it and waiting for the review.
