### ISSUE TITLE
Implement Bottom Navigation Bar

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Frontend#14]
Create the bottom navigation bar with four tabs: Home, Explore, Collections, and Map. Each tab should be clickable and navigate to the corresponding screen.

Check this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=386-8094&t=20CVJBgMkxb3Icl4-1) and this [figma file](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=388-8845&t=20CVJBgMkxb3Icl4-1)

**Comment by hema-k83** [comment]
@TheHappyBaloney  Can you please assign this to me.
