### ISSUE TITLE
Develop Splash Screen

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Frontend#20]
Develop the [Pujo Atlas Splash Screen](https://www.figma.com/design/4ucSjCxyab32J3HdWD639Z/Pujo-Atlas-1.0?node-id=152-277&t=LrWhUE3AjZLEr1Jn-1) that appears when the app is launched, ensuring it is visually appealing and provides a smooth transition to the home screen. 

To contribute or for more details, reach out to the devs at [Pujo Atlas Discord Server](https://discord.com/invite/dPp9jbtRFr) and tag @Flutter Dev on the # repo-issues channel

**Comment by akay25** [comment]
Can I try to work on this issue?
