### ISSUE TITLE
Addition of Missing Project Setup Files

### ISSUE THREAD

**Issue by TheHappyBaloney** [Pujo-Atlas-Kolkata/PujoAtlasKol-Frontend#5]
Some essential project setup files are missing in the Flutter Front End repository. These files are necessary for proper project initialization and configuration. This issue requires adding the missing files and ensuring the project setup is complete and functional.

**Comment by hema-k83** [comment]
@TheHappyBaloney  can you please assign this to me

**Comment by TheHappyBaloney** [comment]
done!
